# Setup
title:               musings
tagline:             'mika adlin'
description:         'mika adlin is a product manager, autodidact programmer, and writer.'
url:                 https://www.mikaadlin.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mika Adlin
  url:               https://www.linkedin.com/in/mika-adlin/
  email:             mikhail.adlin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
